# Generated by Django 4.1.7 on 2023-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_assignedtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='belt',
            field=models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Orange', 'Orange'), ('Purple', 'Purple')], max_length=10),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='category',
            field=models.CharField(choices=[('Nourish', 'Nourish'), ('Move', 'Move'), ('Rest', 'Rest'), ('Connect', 'Connect'), ('Learn', 'Learn'), ('Spark', 'Spark'), ('Challenge', 'Challenge')], max_length=10),
        ),
    ]
