# Generated by Django 4.1.5 on 2023-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_patienttest_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='exam_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Exam Number'),
        ),
    ]
