# Generated by Django 4.1.5 on 2023-03-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_patienttest_exam_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='age',
            field=models.IntegerField(),
        ),
    ]
