# Generated by Django 4.1.5 on 2023-04-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userentrypatienttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
