# Generated by Django 4.1.5 on 2023-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_onboarding_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.CharField(choices=[('Empowered Explorer', 'Empowered Explorer'), ('Tailored Trailblazer', 'Tailored Trailblazer'), ('Personalized Pathfinder', 'Personalized Pathfinder')], max_length=28),
        ),
    ]
