# Generated by Django 4.1.5 on 2023-03-31 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='exam_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
