# Generated by Django 4.1.5 on 2023-04-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_patienttest_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttest',
            name='nourish_grade',
            field=models.IntegerField(blank=True, choices=[(10, '10'), (7, '7'), (5, '5'), (3, '3'), (1, '1')], null=True, verbose_name='Nourish Grade'),
        ),
    ]
