# Generated by Django 4.1.5 on 2023-04-01 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_patienttest_nourish_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntryPatientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('exam_number', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='Exam Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight (lbs)')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height (inches)')),
                ('fasting_glucose', models.IntegerField(verbose_name='Fasting Glucose')),
                ('hga1c', models.IntegerField(verbose_name='HgA1c')),
                ('cprotein', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='C Reactive Protein')),
                ('homocysteine', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Homocysteine')),
                ('fasting_insulin', models.IntegerField(verbose_name='Fasting Insulin')),
                ('ldl_particle', models.IntegerField(verbose_name='LDL Particle Number')),
                ('ldl_size', models.IntegerField(verbose_name='LDL Size')),
                ('insulin_resistance', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Insulin Resistance Score')),
                ('testosterone', models.IntegerField(choices=[(10, '10'), (7, '7'), (5, '5'), (3, '3'), (1, '1')], verbose_name='Testosterone')),
                ('thyroid', models.IntegerField(choices=[(10, '10'), (7, '7'), (5, '5'), (3, '3'), (1, '1')], verbose_name='Thyroid Stimulating Hormone')),
                ('vitamin_d3', models.IntegerField(verbose_name='Vitamin D3')),
                ('vitamin_b12', models.IntegerField(verbose_name='Vitamin B12')),
                ('zinc_rbc', models.IntegerField(verbose_name='Zinc RBC')),
                ('magnesium_rbc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Magnesium RBC')),
                ('omega3_index', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Omega 3 Index')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
